### ISSUE TITLE
[Feature request] allow AND and OR operators in query

### ISSUE THREAD

**Issue by ivohuisjes** [ConsenSys/Mahuta#57]
I would like to search for multiple words on different index-fields. I don't think this is possible?

Example: I want to search for files that have the word "X" in the title OR in a different field.

BTW: thanks so much for developing this great software

**Comment by ivohuisjes** [comment]
I see there is a method in Query.java: public Query fullText(String[] names, String value) {}

My particular usecase is actually a bit more complex, which is not possible I think:
I want to search search for word "X" OR word "Y" in the title OR search for word "X" OR word "Y" in a different field and I want the combined results.

**Comment by gjeanmart** [comment]
As per the refactoring (IPFS-Store to Mahuta), a query can now use the logical operator OR to execute multiple sub-queries and aggregate the result.

**Examples:**
All the results with author equals to _Sylvester Stallone_ OR _Arnold Schwarzenegger_
```
{
  "or": [
    {
      "query": [
        {
          "name": "author",
          "operation": "EQUALS",
          "value": "Sylvester Stallone"
        }
      ]
    },
    {
      "query": [
        {
          "name": "author",
          "operation": "EQUALS",
          "value": "Arnold Schwarzenegger"
        }
      ]
    }
  ]
}
```

> I want to search search for word "X" OR word "Y" in the title OR search for word "X" OR word "Y" in a different field and I want the combined results.

```
{
  "or": [
    {
      "query": [
        {
          "name": "title",
          "operation": "CONTAINS",
          "value": "X"
        }
        ]
    },
    {
      "query": [
        {
          "name": "title",
          "operation": "CONTAINS",
          "value": "Y"
        }
        ]
    },
    {
      "query": [
        {
          "name": "field1",
          "operation": "CONTAINS",
          "value": "X"
        }
        ]
    },
    {
      "query": [
        {
          "name": "field1",
          "operation": "CONTAINS",
          "value": "Y"
        }
        ]
    }  
  ]
}
```
