### ISSUE TITLE
[Feature request] unpin/unindex functionality

### ISSUE THREAD

**Issue by nlko** [ConsenSys/Mahuta#60]
Hello,

I've been searching the API and the code (I'm not a java guy) but I can't find how to unpin and/or unindex a document from the API.

Did I miss something or is it something to be done in the future ?

Nicolas

**Comment by gjeanmart** [comment]
Hey,
Thanks you for this request. I agree this is currently something missing in the API and not necessarily hard to implement. I'll add this in the next release which should be ready beginning of January !

**Comment by gjeanmart** [comment]
As per the refactoring (IPFS-Store to Mahuta), the following API operations have been added:

Operation | Description | Method | URI
-- | -- | -- | --
delete_by_id | Unpin and deindex a file by ID | DELETE | /delete/id/{id}
delete_by_hash | Unpin and deindex a file by Hash | DELETE | /delete/hash/{hash}

**delete_by_id** unindex and unpin from master node and each replicas
**delete_by_hash** only unpin from master node and each replicas
