### ISSUE TITLE
Maven cannot find Mahuta Version

### ISSUE THREAD

**Issue by Straegge** [ConsenSys/Mahuta#84]
```
<dependency>
  <groupId>net.consensys.mahuta</groupId>
  <artifactId>mahuta-core</artifactId>
  <version>0.3.8</version>
</dependency>
```

When I copy the Maven dependency import into my pom.xml, the jars cannot be found. Maven gives me no possibility to find them no matter what version I try. I'm using IntelliJ IDEA 2019.1.3.

**Comment by gjeanmart** [comment]
Hi, Thanks for pointing this out.

The packages are hosted on a specific repo, so you need to this to your `pom.xml`

```
	<repositories>
		<repository>
			<id>consensys-kauri</id>
			<name>consensys-kauri</name>
			<url>https://consensys.bintray.com/kauri/</url>
		</repository>
	</repositories>
```

I should probably mirror the repository with Maven central to offer a wider access without requiring to configure a repo.

Greg

**Comment by Straegge** [comment]
Thank you very much!
